# Generated by Django 3.2.3 on 2021-12-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='prof_pic',
        ),
    ]
