# Generated by Django 3.2.3 on 2022-01-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Ordered', max_length=200, null=True),
        ),
    ]
